repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_fmt
        files: \.(tf|tfvars|tftest\.hcl)$
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/terraform/.tflint.hcl
        files: \.tf$
