name: Deploy
run-name: Deploy to ${{ inputs.environment }}

concurrency:
  group: deploy-${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      server_types:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - qa
          - poc
          - test
          - preview
          - training
          - production
          - copilotmigration
      server_types:
        description: Server types to deploy
        required: true
        type: choice
        options:
          - all
          - web
          - good-job
        default: all

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push-image.yml
  deploy-infrastructure:
    needs: build-and-push-image
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: ${{ inputs.environment }}
  deploy-application:
    needs: deploy-infrastructure
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: ${{ inputs.environment }}
      server_types: ${{ inputs.server_types }}
